import { useEffect, useState } from "react";
import { SilqCompiler } from "../../../backend/src/compiler/SilqCompiler";
import type { CircuitModel } from "../../../backend/src/contracts";
import { StateVectorSimulator } from "../../../simulator/StateVectorSimulator";
import { useIDEStore } from "../store/ideStore";

const compiler = new SilqCompiler(); const simulator = new StateVectorSimulator(compiler);
export function CircuitPanel(): JSX.Element {
  const { tabs, activeTab, log, setPanel, setSimulationOutput } = useIDEStore(); const source = tabs.find((item) => item.id === activeTab)?.content ?? ""; const [circuit, setCircuit] = useState<CircuitModel>({ name: "No circuit", qubits: 1, operations: [] });
  useEffect(() => { let active = true; const timer = window.setTimeout(() => { void compiler.generateCircuit(source).then((value) => { if (active) setCircuit(value); }); }, 150); return () => { active = false; window.clearTimeout(timer); }; }, [source]);
  const run = async () => { try { const result = await simulator.run(source); const report = [`Simulation completed in ${result.elapsedMs}ms`, "", "Probability distribution:", ...Object.entries(result.probabilities).map(([state, value]) => `|${state}⟩  ${(value * 100).toFixed(2)}%`), "", "State vector:", ...result.stateVector, "", "Measurements:", JSON.stringify(result.counts), "", "Bloch vectors:", ...result.registers.map((register) => `q${register.qubit}: (${register.bloch.x.toFixed(3)}, ${register.bloch.y.toFixed(3)}, ${register.bloch.z.toFixed(3)})`)].join("\n"); setSimulationOutput(report); log(`Simulated ${circuit.name}: ${result.shots} shots in ${result.elapsedMs}ms.`); setPanel("simulation"); } catch (error) { log(`Simulation error: ${error instanceof Error ? error.message : String(error)}`); setPanel("problems"); } };
  return <aside className="circuit"><div className="panel-title">QUANTUM CIRCUIT <button onClick={() => void run()}>▶ Run</button></div><div className="circuit-meta"><span>{circuit.name}</span><span>{circuit.qubits} qubits</span></div><CircuitSvg circuit={circuit} /><div className="legend"><span>● Control</span><span>⊕ X gate</span></div><div className="circuit-presets"><p>Live compiler output</p><button onClick={() => void run()}>Run state-vector simulator</button></div></aside>;
}
function CircuitSvg({ circuit }: { circuit: CircuitModel }): JSX.Element { const width = Math.max(190, 64 + circuit.operations.length * 47), height = Math.max(92, circuit.qubits * 43 + 25); return <div className="circuit-svg-wrap"><svg className="circuit-svg" viewBox={`0 0 ${width} ${height}`} aria-label="Quantum circuit"><g>{Array.from({ length: circuit.qubits }, (_, qubit) => <g key={qubit}><text x="4" y={38 + qubit * 43}>q{qubit}</text><line x1="28" x2={width - 6} y1={32 + qubit * 43} y2={32 + qubit * 43} /></g>)}</g>{circuit.operations.map((operation, index) => <Gate key={`${operation.moment}-${index}`} operation={operation} x={48 + index * 47} />)}</svg></div>; }
function Gate({ operation, x }: { operation: CircuitModel["operations"][number]; x: number }): JSX.Element { const targets = operation.targets; const primary = targets[targets.length - 1] ?? 0; const y = 32 + primary * 43; const controlled = ["CX", "CZ"].includes(operation.gate) && targets.length > 1; const controlY = controlled ? 32 + targets[0] * 43 : 0; if (operation.gate === "SWAP") return <g><line x1={x} x2={x} y1={32 + targets[0] * 43} y2={32 + targets[1] * 43} className="gate-link" /><text x={x - 6} y={32 + targets[0] * 43 + 5}>×</text><text x={x - 6} y={32 + targets[1] * 43 + 5}>×</text></g>; return <g>{controlled && <><line x1={x} x2={x} y1={controlY} y2={y} className="gate-link" /><circle cx={x} cy={controlY} r="4" className="control" /></>}<rect x={x - 13} y={y - 13} width="26" height="26" rx="2" className="gate" /><text x={x} y={y + 4} textAnchor="middle">{operation.gate === "CX" ? "⊕" : operation.gate === "MEASURE" ? "M" : operation.gate}</text></g>; }
