import type * as Monaco from "monaco-editor";
import { SilqCompiler } from "../../../backend/src/compiler/SilqCompiler";

const compiler = new SilqCompiler(); let registered = false;
const gates = ["H", "X", "Y", "Z", "S", "T", "CNOT", "CZ", "SWAP", "Measure", "Reset"];
export function registerSilqLanguage(monaco: typeof Monaco): void {
  if (registered) return; registered = true; monaco.languages.register({ id: "silq", extensions: [".silq"], aliases: ["Silq", "silq"] });
  monaco.languages.setMonarchTokensProvider("silq", { tokenizer: { root: [[/\/\/.*/, "comment"], [/\b(fn|let|return|if|else|while|new|measure|reset)\b/, "keyword"], [/\b(Qubit|Bool|Int|Float)\b/, "type"], [/\b(H|X|Y|Z|S|T|CNOT|CZ|SWAP|Measure|Reset)\b/, "operator"], [/[{}()[\]]/, "delimiter"], [/\d+/, "number"]] } });
  monaco.languages.setLanguageConfiguration("silq", { comments: { lineComment: "//" }, brackets: [["{", "}"], ["[", "]"], ["(", ")"]], autoClosingPairs: [{ open: "{", close: "}" }, { open: "[", close: "]" }, { open: "(", close: ")" }, { open: '"', close: '"' }], surroundingPairs: [{ open: "{", close: "}" }, { open: "[", close: "]" }, { open: "(", close: ")" }] });
  const completions = gates.map((gate) => ({ label: gate, kind: monaco.languages.CompletionItemKind.Function, insertText: `${gate}(${gate === "CNOT" || gate === "CZ" || gate === "SWAP" ? "${1:q[0]}, ${2:q[1]}" : "${1:q[0]}"});`, insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet, documentation: gateDocumentation(gate) })) as unknown as Monaco.languages.CompletionItem[];
  const snippets = [{ label: "quantum function", kind: monaco.languages.CompletionItemKind.Snippet, insertText: "fn ${1:main}() {\n  let q = new Qubit[${2:2}];\n  ${0}\n}", insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet, documentation: "Define a new quantum function" }] as unknown as Monaco.languages.CompletionItem[];
  monaco.languages.registerCompletionItemProvider("silq", { triggerCharacters: ["("], provideCompletionItems: () => ({ suggestions: [...completions, ...snippets] }) });
  monaco.languages.registerHoverProvider("silq", { provideHover: (model, position) => { const word = model.getWordAtPosition(position); return word ? { contents: [{ value: `**${word.word}**\n\n${gateDocumentation(word.word)}` }] } : null; } });
  monaco.languages.registerDocumentSymbolProvider("silq", { provideDocumentSymbols: async (model) => { const analysis = await compiler.analyze(model.getValue()); const symbols: Monaco.languages.DocumentSymbol[] = []; const visit = (nodes: typeof analysis.ast.body, bucket: Monaco.languages.DocumentSymbol[]): void => nodes.forEach((node) => { const range = toRange(monaco, model, node.range); const children: Monaco.languages.DocumentSymbol[] = []; const item: Monaco.languages.DocumentSymbol = { name: node.kind === "Function" ? node.name : node.kind === "Gate" ? node.gate : "name" in node ? node.name : node.kind, detail: node.kind, kind: node.kind === "Function" ? monaco.languages.SymbolKind.Function : node.kind === "Gate" ? monaco.languages.SymbolKind.Method : monaco.languages.SymbolKind.Variable, range, selectionRange: range, children, tags: [] }; bucket.push(item); if (node.kind === "Function") visit(node.body, children); }); visit(analysis.ast.body, symbols); return symbols; } });
  monaco.languages.registerFoldingRangeProvider("silq", { provideFoldingRanges: async (model) => { const analysis = await compiler.analyze(model.getValue()); const ranges: Monaco.languages.FoldingRange[] = []; const visit = (nodes: typeof analysis.ast.body): void => nodes.forEach((node) => { if (node.kind === "Function") { const end = model.getPositionAt(node.range.end).lineNumber; ranges.push({ start: node.range.line, end }); visit(node.body); } }); visit(analysis.ast.body); return ranges; } });
  monaco.languages.registerDefinitionProvider("silq", { provideDefinition: async (model, position) => { const word = model.getWordAtPosition(position); if (!word) return null; const analysis = await compiler.analyze(model.getValue()); const symbol = analysis.semantic.symbols.get(word.word); return symbol ? { uri: model.uri, range: toRange(monaco, model, symbol.range) } : null; } });
  monaco.languages.registerRenameProvider("silq", { provideRenameEdits: async (model, position, nextName) => { const word = model.getWordAtPosition(position); if (!word || !/^[A-Za-z_]\w*$/.test(nextName)) return { edits: [], rejectReason: "Choose a valid identifier." }; const matches = model.findMatches(`\\b${escape(word.word)}\\b`, false, true, false, null, true); return { edits: matches.map((match) => ({ resource: model.uri, textEdit: { range: match.range, text: nextName }, versionId: model.getVersionId() })) }; }, resolveRenameLocation: (model, position) => { const word = model.getWordAtPosition(position); return word ? { range: new monaco.Range(position.lineNumber, word.startColumn, position.lineNumber, word.endColumn), text: word.word } : null; } });
  monaco.languages.registerDocumentFormattingEditProvider("silq", { provideDocumentFormattingEdits: (model) => [{ range: model.getFullModelRange(), text: formatSilq(model.getValue()) }] });
  monaco.editor.defineTheme("silq-dark", { base: "vs-dark", inherit: true, rules: [{ token: "operator", foreground: "7dd3fc" }, { token: "type", foreground: "c4b5fd" }], colors: { "editor.background": "#11151d" } }); monaco.editor.defineTheme("silq-light", { base: "vs", inherit: true, rules: [{ token: "operator", foreground: "0369a1" }], colors: {} });
}
export async function updateSilqDiagnostics(monaco: typeof Monaco, model: Monaco.editor.ITextModel): Promise<void> { const diagnostics = await compiler.diagnostics(model.getValue()); monaco.editor.setModelMarkers(model, "silq", diagnostics.map((item) => ({ severity: item.severity === "error" ? monaco.MarkerSeverity.Error : item.severity === "warning" ? monaco.MarkerSeverity.Warning : monaco.MarkerSeverity.Info, message: item.message, startLineNumber: item.line, startColumn: item.column, endLineNumber: item.line, endColumn: item.column + 1 }))); }
function toRange(monaco: typeof Monaco, model: Monaco.editor.ITextModel, range: { start: number; end: number }): Monaco.IRange { const start = model.getPositionAt(range.start), end = model.getPositionAt(range.end); return new monaco.Range(start.lineNumber, start.column, end.lineNumber, end.column); }
function gateDocumentation(name: string): string { const map: Record<string, string> = { H: "Hadamard: creates equal superposition.", X: "Pauli-X: flips a qubit.", Y: "Pauli-Y rotation.", Z: "Pauli-Z phase flip.", S: "π/2 phase gate.", T: "π/4 phase gate.", CNOT: "Controlled NOT on two qubits.", CZ: "Controlled phase flip.", SWAP: "Exchanges two qubit states.", Measure: "Measures a qubit.", Reset: "Resets a qubit to |0⟩." }; return map[name] ?? "Silq symbol."; }
function formatSilq(source: string): string { let depth = 0; return source.split("\n").map((line) => { const trimmed = line.trim(); if (trimmed.startsWith("}")) depth = Math.max(0, depth - 1); const formatted = `${"  ".repeat(depth)}${trimmed}`; if (trimmed.endsWith("{")) depth++; return formatted; }).join("\n"); }
function escape(value: string): string { return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
